{{- if and .Values.certificate.enabled (not .Values.ingressGrpc.tlsSecretName) }}
{{- $certificate := .Values.certificate }}
{{- range $chain := .Values.chains }}
{{- $domainName := printf "%s.%s" (lower $chain.name) (include "provider.domain" $) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "provider.fullname" $ }}-{{ $chain.name | lower }}-tls
  namespace: {{ include "provider.namespace" $ }}
  labels:
    {{- include "provider.labels" $ | nindent 4 }}
  {{- with $certificate.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  commonName: {{ $domainName }}
  dnsNames:
    - {{ $domainName }}
    {{- range $certificate.additionalHosts }}
    - {{ . | quote }}
    {{- end }}
  {{- with $certificate.duration }}
  duration: {{ . | quote }}
  {{- end }}
  {{- with $certificate.renewBefore }}
  renewBefore: {{ . | quote }}
  {{- end }}
  issuerRef:
    {{- with $certificate.issuer.group }}
    group: {{ . | quote }}
    {{- end }}
    kind: {{ $certificate.issuer.kind | quote }}
    name: {{ $certificate.issuer.name | quote }}
  {{- if $certificate.privateKey.enabled }}
  {{- with $certificate.privateKey }}
  privateKey:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  secretName: {{ include "provider.fullname" $ }}-{{ $chain.name | lower }}-tls
  {{- with $certificate.secretTemplateAnnotations }}
  secretTemplate:
    annotations:
      {{- range $key, $value := . }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
  {{- end }}
  {{- with $certificate.usages }}
  usages:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
