{{- if .Values.ingressGrpc.enabled }}
{{- range $chain := $.Values.chains }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "provider.fullname" $ }}-{{ $chain.name | lower }}
  labels:
    {{- include "provider.labels" $ | nindent 4 }}
  {{- with $.Values.ingressGrpc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $.Values.ingressGrpc.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if $.Values.ingressGrpc.tls }}
  tls:
    - hosts:
        - "{{ $chain.name | lower }}.{{ include "provider.domain" $ }}"
      secretName: {{ default (printf "%s-%s-tls" (include "provider.fullname" $) ($chain.name | lower)) $chain.tlsSecretName }}
  {{- end }}
  rules:
    - host: "{{ $chain.name | lower }}.{{ include "provider.domain" $ }}"
      http:
        paths:
          - path: {{ $.Values.ingressGrpc.path }}
            pathType: {{ $.Values.ingressGrpc.pathType }}
            backend:
              service:
                name: {{ include "provider.fullname" $ }}-{{ $chain.name | lower }}
                port:
                  name: grpc
{{- end }}
{{- end }}
