apiVersion: v2
name: lava-provider
description: |
  Lava helm chart for the provider service
icon: https://github.com/lavanet/helm-charts/blob/main/docs/logo/logo.png?raw=true
sources:
  - https://github.com/lavanet/helm-charts
type: application
version: 1.0.8
appVersion: "v6.2.4"
kubeVersion: ">=1.25.0-0"
home: https://lavanet.xyz
keywords:
  - provider
  - blockchain
  - web3
maintainers:
  - name: Impulse
    url: https://impulse.expert
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/prerelease: "false"
  images: |
    - name: provider
      image: ghcr.io/lavanet/lava/lavap
